[2024-12-05T14:44:00.977+0100] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-05T14:44:00.990+0100] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_warehouse_etl_standard.load_fact_table manual__2024-12-05T13:33:29.205192+00:00 [queued]>
[2024-12-05T14:44:00.992+0100] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_warehouse_etl_standard.load_fact_table manual__2024-12-05T13:33:29.205192+00:00 [queued]>
[2024-12-05T14:44:00.992+0100] {taskinstance.py:2866} INFO - Starting attempt 2 of 3
[2024-12-05T14:44:00.999+0100] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): load_fact_table> on 2024-12-05 13:33:29.205192+00:00
[2024-12-05T14:44:01.004+0100] {standard_task_runner.py:72} INFO - Started process 61996 to run task
[2024-12-05T14:44:01.007+0100] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'data_warehouse_etl_standard', 'load_fact_table', 'manual__2024-12-05T13:33:29.205192+00:00', '--job-id', '86', '--raw', '--subdir', 'DAGS_FOLDER/data_warehouse_etl_dag.py', '--cfg-path', '/var/folders/4k/bhptqqm131v6f034phck6fc80000gn/T/tmp2dg_bb_p']
[2024-12-05T14:44:01.009+0100] {standard_task_runner.py:105} INFO - Job 86: Subtask load_fact_table
[2024-12-05T14:44:01.035+0100] {task_command.py:467} INFO - Running <TaskInstance: data_warehouse_etl_standard.load_fact_table manual__2024-12-05T13:33:29.205192+00:00 [running]> on host sijibomis-mbp
[2024-12-05T14:44:01.059+0100] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data_engineering' AIRFLOW_CTX_DAG_ID='data_warehouse_etl_standard' AIRFLOW_CTX_TASK_ID='load_fact_table' AIRFLOW_CTX_EXECUTION_DATE='2024-12-05T13:33:29.205192+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-05T13:33:29.205192+00:00'
[2024-12-05T14:44:01.060+0100] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-05T14:44:01.136+0100] {load.py:124} INFO - Loaded 456 fact table records
[2024-12-05T14:44:01.137+0100] {python.py:240} INFO - Done. Returned value was: True
[2024-12-05T14:44:01.141+0100] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-05T14:44:01.142+0100] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=data_warehouse_etl_standard, task_id=load_fact_table, run_id=manual__2024-12-05T13:33:29.205192+00:00, execution_date=20241205T133329, start_date=20241205T134400, end_date=20241205T134401
[2024-12-05T14:44:01.151+0100] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-05T14:44:01.156+0100] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-05T14:44:01.157+0100] {local_task_job_runner.py:245} INFO - ::endgroup::
